name: Release ZIP on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload ZIP as Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: SRZGTimeCalc.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
